[app]
port = "8002"
host = "127.0.0.1"
redis_uri = "redis://192.168.2.2:6379/9"
cookie_secret = "QRt73RtEeSUMiC4lpIlVvusHgfS6LtunWrKauxaeauNWBSFMKqSDS7baJOmokN2dn3PJmtKjMwSRrfr7"
template_base_dir = "public/templates/**/*.html"
[db]
host = "192.168.2.2"
username = "postgres"
password = "password"
port = "5432"
database = "some_name"
pool_timeout_seconds = 2
require_ssl = false